services:
  nestjs-boilerplate-postgres:
    container_name: nestjs-boilerplate-postgres
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - nestjs-boilerplate-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    env_file: .env.prod
    networks:
      - nestjs-boilerplate-network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: nestjs-boilerplate-postgres

  nestjs-boilerplate-redis:
    container_name: nestjs-boilerplate-redis
    image: redis:8.0.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - nestjs-boilerplate-redis-data:/data
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: ${REDIS_DATABASES}
    env_file: .env.prod
    networks:
      - nestjs-boilerplate-network
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: nestjs-boilerplate-redis

  nestjs-boilerplate:
    container_name: nestjs-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      nestjs-boilerplate-postgres:
        condition: service_healthy
      nestjs-boilerplate-redis:
        condition: service_healthy
    env_file: .env.prod
    networks:
      - nestjs-boilerplate-network
    hostname: nestjs-boilerplate

volumes:
  nestjs-boilerplate-postgres-data:
    name: nestjs-boilerplate-postgres-data
    driver: local
  nestjs-boilerplate-redis-data:
    name: nestjs-boilerplate-redis-data
    driver: local

networks:
  nestjs-boilerplate-network:
    name: nestjs-boilerplate-network
    driver: bridge
    attachable: true
