services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    env_file: .env
    networks:
      - network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: postgres

  redis:
    container_name: redis
    image: redis:8.0.2-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/data
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: ${REDIS_DATABASES}
    env_file: .env
    networks:
      - network
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: redis

  # redis-insight:
  #   container_name: redis-insight
  #   image: redislabs/redisinsight:latest
  #   restart: always
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - ${RI_PORT}:${RI_PORT}
  #   volumes:
  #     - redis-insight-data:/usr/src/app/redisinsight/api/data
  #   environment:
  #     REDISINSIGHT_DISABLE_ENCRYPTION: ${RI_DISABLE_ENCRYPTION}
  #   env_file: .env
  #   networks:
  #     - network
  #   command: |
  #     sh -c " mkdir -p /usr/src/app/redisinsight/api/data && chown -R node:node /usr/src/app/redisinsight/api/data && ./docker-entry.sh "
  #   hostname: redis-insight
  #   user: "0:0"

  # kafka-broker:
  #   container_name: kafka-broker
  #   image: apache/kafka:latest
  #   ports:
  #     - ${KAFKA_PORT}:${KAFKA_PORT}
  #     - ${KAFKA_CONTROLLER_PORT}:${KAFKA_CONTROLLER_PORT}
  #   environment:
  #     KAFKA_NODE_ID: ${KAFKA_NODE_ID}
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:${KAFKA_PORT}
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@kafka-broker:${KAFKA_CONTROLLER_PORT}
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
  #     KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
  #   env_file: .env
  #   networks:
  #     - network
  #   hostname: kafka-broker

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   depends_on:
  #     - kafka-broker
  #   ports:
  #     - ${KAFKA_UI_PORT}:${KAFKA_UI_PORT}
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:${KAFKA_PORT}
  #   env_file: .env
  #   networks:
  #     - network
  #   hostname: kafka-ui

volumes:
  postgres-data:
    name: postgres-data
    driver: local
  redis-data:
    name: redis-data
    driver: local
  # redis-insight-data:
  #   name: redis-insight-data
  #   driver: local

networks:
  network:
    name: network
    driver: bridge
    attachable: true
